version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pg-django-dev
    environment:
      POSTGRES_DB: dp_ses
      POSTGRES_USER: joaob
      POSTGRES_PASSWORD: 36457454
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data_dev:
  pgadmin_data:

