# Generated by Django 5.2.4 on 2025-07-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=50, unique=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('numero_conselho', models.CharField(blank=True, max_length=50, null=True)),
                ('uf_conselho', models.CharField(blank=True, max_length=2, null=True)),
                ('conselho', models.CharField(blank=True, max_length=50, null=True)),
                ('setor', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('dias', models.CharField(max_length=50)),
                ('jornada', models.CharField(max_length=50)),
                ('contrato', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('data_admissao', models.DateField()),
                ('nome_mae', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField()),
                ('naturalidade', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=50)),
                ('titulo_eleitoral', models.CharField(max_length=20)),
                ('zona', models.CharField(max_length=10)),
                ('secao', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=2)),
                ('rg', models.CharField(max_length=20)),
                ('orgao_expeditor', models.CharField(max_length=20)),
                ('uf_rg', models.CharField(max_length=2)),
                ('ctps_numero', models.CharField(max_length=20)),
                ('ctps_serie', models.CharField(max_length=20)),
                ('ctps_uf', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('documento_militar', models.CharField(blank=True, max_length=50, null=True)),
                ('grau_instrucao', models.CharField(max_length=50)),
                ('pasep', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('fixo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf_endereco', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
    ]
