# Generated by Django 5.2.3 on 2025-07-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_ses_management', '0002_colaborador_delete_tarefasmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='orgao_expeditor',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='uf_rg',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('Médico', 'Médico'), ('Enfermeiro', 'Enfermeiro'), ('Técnico de Enfermagem', 'Técnico de Enfermagem'), ('Auxiliar Administrativo', 'Auxiliar Administrativo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro(a)', 'Solteiro(a)'), ('casado(a)', 'Casado(a)'), ('divorciado(a)', 'Divorciado(a)'), ('viúvo(a)', 'Viúvo(a)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rg',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='turno',
            field=models.CharField(choices=[('manhã', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10),
        ),
    ]
