# Generated by Django 5.2.3 on 2025-07-14 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_ses_management', '0003_remove_colaborador_orgao_expeditor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='conselho',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='ctps_numero',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='ctps_serie',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='ctps_uf',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='fixo',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='jornada',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='pasep',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='secao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='titulo_eleitoral',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='uf_endereco',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='zona',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='dias_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dias de trabalho'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado_vota',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado onde vota'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='jornada_trabalho',
            field=models.CharField(default='', max_length=100, verbose_name='Jornada de trabalho'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_completo',
            field=models.CharField(default='Nome Padrão', max_length=150, verbose_name='Nome completo'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_conselho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do conselho'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='numero_ctps',
            field=models.CharField(default='', max_length=20, verbose_name='Número da CTPS'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='numero_pasep',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número do PASEP'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='rg_completo',
            field=models.CharField(default='', max_length=50, verbose_name='RG COMPLETO (Número e texto)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='secao_eleitoral',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Seção eleitoral'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='serie_ctps',
            field=models.CharField(default='', max_length=20, verbose_name='Série da CTPS'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='setor_trabalho',
            field=models.CharField(default='', max_length=100, verbose_name='Setor de trabalho'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone fixo'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(default='', max_length=100, verbose_name='Tipo de contrato'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Título de eleitor'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='uf',
            field=models.CharField(default='', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='uf_ctps',
            field=models.CharField(default='', max_length=2, verbose_name='UF da CTPS'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='zona_eleitoral',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zona eleitoral'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='bairro',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('medico', 'Médico'), ('enfermeiro', 'Enfermeiro'), ('tec_enfermagem', 'Técnico de Enfermagem'), ('aux_admin', 'Auxiliar Administrativo')], default='aux_admin', max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='celular',
            field=models.CharField(default='', max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cep',
            field=models.CharField(default='', max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(default='', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='documento_militar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento militar'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='endereco',
            field=models.CharField(default='', max_length=150, verbose_name='Endereço (rua/avenida)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], default='solteiro', max_length=10, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(default='', max_length=100, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='grau_instrucao',
            field=models.CharField(default='', max_length=50, verbose_name='Grau de instrução'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula (código funcional)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='naturalidade',
            field=models.CharField(default='', max_length=100, verbose_name='Naturalidade (cidade/estado)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_mae',
            field=models.CharField(default='', max_length=150, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do pai'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero',
            field=models.CharField(default='', max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero_conselho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do conselho profissional'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='registro',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Registro (código interno)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='manha', max_length=10, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='uf_conselho',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do conselho'),
        ),
    ]
