# Generated by Django 5.2.4 on 2025-07-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_ses_management', '0004_remove_colaborador_conselho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='id',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='registro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor_trabalho',
            field=models.CharField(choices=[('emergencia', 'Emergência'), ('uti', 'UTI'), ('enfermaria', 'Enfermaria'), ('administrativo', 'Administrativo'), ('cozinha', 'Cozinha'), ('higienizacao', 'Higienização')], default='enfermaria', max_length=100, verbose_name='Setor de trabalho'),
        ),
    ]
