# Generated by Django 5.2.4 on 2025-07-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_ses_management', '0005_remove_colaborador_id_alter_colaborador_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='observacoes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observações (informações adicionais)'),
        ),
    ]
