# Generated by Django 5.2.4 on 2025-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_ses_management', '0006_colaborador_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='setor_trabalho',
            field=models.CharField(choices=[('emergencia', 'Emergência'), ('uti', 'UTI'), ('enfermaria', 'Enfermaria'), ('administrativo', 'Administrativo'), ('cozinha', 'Cozinha'), ('higienizacao', 'Higienização'), ('Farmácia', 'Farmácia')], default='enfermaria', max_length=100, verbose_name='Setor de trabalho'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('ferias', 'Férias'), ('afastado', 'Afastado')], default='ativo', max_length=10, verbose_name='Status'),
        ),
    ]
