# Generated by Django 5.2.4 on 2025-07-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_ses_management', '0007_alter_colaborador_setor_trabalho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('medico', 'Médico'), ('enfermeiro', 'Enfermeiro'), ('tec_enfermagem', 'Técnico de Enfermagem'), ('aux_admin', 'Auxiliar Administrativo'), ('coordenador', 'Coordenador'), ('gerente', 'Gerente')], default='aux_admin', max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='celular',
            field=models.CharField(max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cep',
            field=models.CharField(max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='endereco',
            field=models.CharField(max_length=150, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], default='solteiro', max_length=20, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(max_length=100, verbose_name='Função Específica'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='grau_instrucao',
            field=models.CharField(max_length=50, verbose_name='Grau de instrução'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='jornada_trabalho',
            field=models.CharField(max_length=100, verbose_name='Jornada de trabalho (Ex: 8h/dia)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(default='000000', max_length=50, unique=True, verbose_name='Matrícula (código funcional)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='naturalidade',
            field=models.CharField(max_length=100, verbose_name='Naturalidade (cidade/estado)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_completo',
            field=models.CharField(max_length=150, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_mae',
            field=models.CharField(max_length=150, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero_ctps',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número da CTPS'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rg_completo',
            field=models.CharField(max_length=50, verbose_name='RG (Número e órgão emissor)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='serie_ctps',
            field=models.CharField(max_length=20, verbose_name='Série da CTPS'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor_trabalho',
            field=models.CharField(choices=[('emergencia', 'Emergência'), ('uti', 'UTI'), ('enfermaria', 'Enfermaria'), ('administrativo', 'Administrativo'), ('cozinha', 'Cozinha'), ('higienizacao', 'Higienização'), ('farmacia', 'Farmácia')], default='enfermaria', max_length=100, verbose_name='Setor de trabalho'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(max_length=100, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], default='manha', max_length=10, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='uf_ctps',
            field=models.CharField(max_length=2, verbose_name='UF da CTPS'),
        ),
    ]
